### ISSUE TITLE
[feat] Category - 뷰 작업

### ISSUE THREAD

**Issue by SooY2** [DO-SOPT-CDS-5/EQL-Client#13]
## 🛠 Issue

카테고리 페이지 기본 레이아웃 작업하기
-
## 📝 To-do

- [x] 네비게이션 바와 상품부분나누기
- [x] 네비바 내부에서 카테고리이름과 카테고리item들 기본틀 작업
- [x] 네비바 스타일링 (내렸을 때 애니매이션 말고)
