### ISSUE TITLE
[Feat] 전체 - svg 세팅 추가 설정 + svg 사용컨벤션

### ISSUE THREAD

**Issue by ljh0608** [DO-SOPT-CDS-5/EQL-Client#7]
## 🛠 Issue

- svg 사용에 대한 추가 설정을 더하는 이슈
## 📝 To-do

- [x] svg.d.ts 파일 생성
- [x] svg.d.ts 파일 tsconfig에 적용
- [x] svg globalStyle cursor pointer 적용
